### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andyferris** [xofbd/pandas_vs_PostgreSQL#5]
Hi - quick query - I wanted to replicate your benchmark comparing some other packages and possibly even push some code (basically, reproduce create_dataset.py in Julia) into other github repositories and I couldn't find a "license" in this repository. Would you consider it to be OK for me to use your code in this way?

**Comment by xofbd** [comment]
Hi Andy,

Thanks for showing interest in my code. I haven't thought about licencing
but I'd like to have some open source licence. Can you give me a day or two
to decide?

**Comment by andyferris** [comment]
Sure, no worries :) For what it's worth, I've been using MIT on my projects.

**Comment by xofbd** [comment]
I've added the MIT licence
